@startuml
'https://plantuml.com/class-diagram

class HeroAircraft





class HeroAircraft {
    {static} - HeroAircraft:heroAircraft
    -HeroAircraft()
    {static}+getHeroAircraft():HeroAircraft
}
note left of HeroAircraft::HeroAircraft
HeroAircraft的实例字段，一个本类的对象
end note

note right of HeroAircraft::HeroAircraft()
私有的构造方法
end note

note left of HeroAircraft::getHeroAircraft()
获取HeroAircraft对象的方法
end note

@enduml