@startuml
'https://plantuml.com/class-diagram

interface Plane

class HeroAircraft
class client

Plane <|.. HeroAircraft



class HeroAircraft {
    {static} - HeroAircraft:heroAircraft
    -HeroAircraft()
    {static}+getHeroAircraft():HeroAircraft
}



@enduml